/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * Order IT Youth API
 * OpenAPI spec version: 0.1.0
 */

export type CreateOrderInputItemsItem = {
  productId: string;
  /** @minimum 1 */
  qty: number;
};
