/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * Order IT Youth API
 * OpenAPI spec version: 0.1.0
 */
import type { CreateOrderInputItemsItem } from './createOrderInputItemsItem';
import type { CreateOrderInputMethod } from './createOrderInputMethod';

export interface CreateOrderInput {
  items: CreateOrderInputItemsItem[];
  method: CreateOrderInputMethod;
}
