/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * Order IT Youth API
 * OpenAPI spec version: 0.1.0
 */

export type CreateOrderInputMethod = typeof CreateOrderInputMethod[keyof typeof CreateOrderInputMethod];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CreateOrderInputMethod = {
  COD: 'COD',
  VIETQR: 'VIETQR',
} as const;
